Problem statement : Create a ML model, which has ability to predict the patient as positive if they are actually positive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/diabetes - diabetes.csv')

In [ ]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
for i in ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']:
  df[i] = df[i].replace(0,np.nan)
  df[i].fillna(df[i].mean(),inplace=True)

In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.686763      72.405184      29.153420  155.548223   
std       3.369578   30.435949      12.096346       8.790942   85.021108   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      25.000000  121.500000   
50%       3.000000  117.000000      72.202592      29.153420  155.548223   
75%       6.000000  140.250000      80.000000      32.000000  155.548223   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    32.457464                  0.471876   33.240885    0.348958  
std      6.875151                  0.331329   11.760232    0.476951  
min     18.200000                  0.078000   21.000000    0.000000  
25%     27.500000                  0.243750   24.000000    0.000000  
50%     32.400000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
df.drop('Pregnancies',axis=1,inplace=True)

In [ ]:
df

Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0      148.0           72.0       35.00000  155.548223  33.6   
1       85.0           66.0       29.00000  155.548223  26.6   
2      183.0           64.0       29.15342  155.548223  23.3   
3       89.0           66.0       23.00000   94.000000  28.1   
4      137.0           40.0       35.00000  168.000000  43.1   
..       ...            ...            ...         ...   ...   
763    101.0           76.0       48.00000  180.000000  32.9   
764    122.0           70.0       27.00000  155.548223  36.8   
765    121.0           72.0       23.00000  112.000000  26.2   
766    126.0           60.0       29.15342  155.548223  30.1   
767     93.0           70.0       31.00000  155.548223  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [ ]:
x = df.iloc[:,:-1]

y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logreg = LogisticRegression()

In [ ]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = logreg.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)

In [ ]:
print(f"Accuracy : {ac}\n{cm}\n\n{cr}")

Accuracy : 0.7359307359307359
[[123  28]
 [ 33  47]]

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       151
           1       0.63      0.59      0.61        80

    accuracy                           0.74       231
   macro avg       0.71      0.70      0.70       231
weighted avg       0.73      0.74      0.73       231



Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss = StandardScaler()

In [ ]:
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [ ]:
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)

print(f"Accuracy : {ac}\n{cm}\n\n{cr}")

Accuracy : 0.7359307359307359
[[123  28]
 [ 33  47]]

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       151
           1       0.63      0.59      0.61        80

    accuracy                           0.74       231
   macro avg       0.71      0.70      0.70       231
weighted avg       0.73      0.74      0.73       231



In [ ]:
print(f"Actual Values     : {y_test[:25].values}")
print(f"Predicted Values  : {y_pred[:25]}")

Actual Values     : [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0]
Predicted Values  : [0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0]


In [ ]:
print(f"Actual Values     : {y_test[25:51].values}")
print(f"Predicted Values  : {y_pred[25:51]}")

Actual Values     : [1 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0]
Predicted Values  : [1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0]


**Predict Probabilities**

In [ ]:
logreg.predict_proba(X_test)

array([[0.74554536, 0.25445464],
       [0.81654785, 0.18345215],
       [0.88943586, 0.11056414],
       [0.89624555, 0.10375445],
       [0.52582517, 0.47417483],
       [0.53747187, 0.46252813],
       [0.98838211, 0.01161789],
       [0.57850631, 0.42149369],
       [0.40761503, 0.59238497],
       [0.19313038, 0.80686962],
       [0.83173059, 0.16826941],
       [0.08612575, 0.91387425],
       [0.54490175, 0.45509825],
       [0.77678343, 0.22321657],
       [0.94605923, 0.05394077],
       [0.61626878, 0.38373122],
       [0.88710068, 0.11289932],
       [0.94542692, 0.05457308],
       [0.24916573, 0.75083427],
       [0.36548434, 0.63451566],
       [0.80484827, 0.19515173],
       [0.92085619, 0.07914381],
       [0.61924945, 0.38075055],
       [0.90664464, 0.09335536],
       [0.51868212, 0.48131788],
       [0.11282231, 0.88717769],
       [0.91472791, 0.08527209],
       [0.96992235, 0.03007765],
       [0.69906457, 0.30093543],
       [0.90001213, 0.09998787],
       [0.

In [ ]:
y_predprob = logreg.predict_proba(X_test)[:,1]

In [ ]:
y_predprob #probability of a patient for being diabetic i.e for class 1

array([0.25445464, 0.18345215, 0.11056414, 0.10375445, 0.47417483,
       0.46252813, 0.01161789, 0.42149369, 0.59238497, 0.80686962,
       0.16826941, 0.91387425, 0.45509825, 0.22321657, 0.05394077,
       0.38373122, 0.11289932, 0.05457308, 0.75083427, 0.63451566,
       0.19515173, 0.07914381, 0.38075055, 0.09335536, 0.48131788,
       0.88717769, 0.08527209, 0.03007765, 0.30093543, 0.09998787,
       0.93811511, 0.88751944, 0.86685705, 0.69795704, 0.63160449,
       0.64237527, 0.9798277 , 0.24100024, 0.37800025, 0.56607105,
       0.04970382, 0.60899855, 0.52820468, 0.18711783, 0.02270265,
       0.5889157 , 0.63089112, 0.16897646, 0.26437267, 0.97774577,
       0.03523017, 0.64948123, 0.83248358, 0.24247613, 0.13707173,
       0.03140807, 0.80543564, 0.0472294 , 0.387484  , 0.7770711 ,
       0.69455594, 0.33637365, 0.26242586, 0.12397569, 0.09447231,
       0.6951337 , 0.03740793, 0.77562687, 0.03705641, 0.89566398,
       0.73807157, 0.0548183 , 0.12750307, 0.12529627, 0.06810

In [ ]:
from sklearn.preprocessing import binarize

In [ ]:
y_pred = binarize([y_predprob],threshold = 0.4)[0]

In [ ]:
y_pred

array([0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 1.

In [ ]:
print(f"Actual Values     : {y_test[:25].values}")
print(f"Predicted Values  : {y_pred[:25].astype(int)}")

Actual Values     : [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0]
Predicted Values  : [0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1]


In [ ]:
print(f"Actual Values     : {y_test[25:51].values}")
print(f"Predicted Values  : {y_pred[25:51].astype(int)}")

Actual Values     : [1 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0]
Predicted Values  : [1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)

print(f"Accuracy : {ac}\n{cm}\n\n{cr}")

Accuracy : 0.70995670995671
[[116  35]
 [ 32  48]]

              precision    recall  f1-score   support

           0       0.78      0.77      0.78       151
           1       0.58      0.60      0.59        80

    accuracy                           0.71       231
   macro avg       0.68      0.68      0.68       231
weighted avg       0.71      0.71      0.71       231



In [ ]:
y_pred = binarize([y_predprob],threshold = 0.3)[0]

y_pred

array([0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 0., 1.

In [ ]:
print(f"Actual Values     : {y_test[:25].values}")
print(f"Predicted Values  : {y_pred[:25].astype(int)}")

Actual Values     : [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0]
Predicted Values  : [0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 1]


In [ ]:
print(f"Actual Values     : {y_test[25:51].values}")
print(f"Predicted Values  : {y_pred[25:51].astype(int)}")

Actual Values     : [1 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0]
Predicted Values  : [1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 0]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)

print(f"Accuracy : {ac}\n{cm}\n\n{cr}")

Accuracy : 0.6926406926406926
[[102  49]
 [ 22  58]]

              precision    recall  f1-score   support

           0       0.82      0.68      0.74       151
           1       0.54      0.72      0.62        80

    accuracy                           0.69       231
   macro avg       0.68      0.70      0.68       231
weighted avg       0.73      0.69      0.70       231



In [ ]:
y_pred = binarize([y_predprob],threshold = 0.1)[0]

y_pred

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 0., 1., 0., 1.

In [ ]:
print(f"Actual Values     : {y_test[:25].values}")
print(f"Predicted Values  : {y_pred[:25].astype(int)}")

Actual Values     : [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0]
Predicted Values  : [1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 0 1 0 1]


In [ ]:
print(f"Actual Values     : {y_test[25:51].values}")
print(f"Predicted Values  : {y_pred[25:51].astype(int)}")

Actual Values     : [1 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0]
Predicted Values  : [1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)

print(f"Accuracy : {ac}\n{cm}\n\n{cr}")

Accuracy : 0.5627705627705628
[[53 98]
 [ 3 77]]

              precision    recall  f1-score   support

           0       0.95      0.35      0.51       151
           1       0.44      0.96      0.60        80

    accuracy                           0.56       231
   macro avg       0.69      0.66      0.56       231
weighted avg       0.77      0.56      0.54       231

